var produtos = [
    {
        id: 1,
        img: 'img/iphones/iphone-SE.jpg',
        nome: 'iPhone SE',
        descrcao: 'teste',
        category: 'iphone',
        price: 4299,
        quantity: 1,
    },
    {
        id: 2,
        img: 'img/iphones/iphone-13.jpg',
        nome: 'iPhone 13',
        descrcao: 'teste',
        category: 'iphone',
        price: 5499,
        quantity: 1,
    },
    {
        id: 3,
        img: 'img/iphones/iphone-14.jpg',
        nome: 'iPhone 14',
        descrcao: 'teste',
        category: 'iphone',
        price: 5999,
        quantity: 1,
    },
    {
        id: 4,
        img: 'img/iphones/iphone14plus.png',
        nome: 'iPhone 14 Plus',
        descrcao: 'teste',
        category: 'iphone',
        price: 6499,
        quantity: 1,
    },
    {
        id: 5,
        img: 'img/iphones/iphone-15.jpg',
        nome: 'iPhone 15',
        descrcao: 'teste',
        category: 'iphone',
        price: 7299,
        quantity: 1,
    },
    {
        id: 6,
        img: 'img/iphones/iphone15plus.png',
        nome: 'iPhone 15 Plus',
        descrcao: 'teste',
        category: 'iphone',
        price: 8299,
        quantity: 1,
    },
    {
        id: 7,
        img: 'img/iphones/iphone-15-pro.jpg',
        nome: 'iPhone 15 Pro',
        descrcao: 'teste',
        category: 'iphone',
        price: 9299,
        quantity: 1,
    },
    {
        id: 8,
        img: 'img/iphones/iphone15promax.png',
        nome: 'iPhone 15 Pro Max',
        descrcao: 'teste',
        category: 'iphone',
        price: 10999,
        quantity: 1,
    },
    {
        id: 9,
        img: 'img/iphones/ipad-card.jpg',
        nome: 'ipad mini',
        descrcao: 'teste',
        category: 'ipad',
        price: 5999,
        quantity: 1,
    },
    {
        id: 10,
        img: 'img/iphones/ipad-9.jpg',
        nome: 'iPadiPad (9ª geração)',
        descrcao: 'teste',
        category: 'ipad',
        price: 3799,
        quantity: 1,
    },
    {
        id: 11,
        img: 'img/iphones/ipad-10.jpg',
        nome: 'iPadiPad (10ª geração)',
        descrcao: 'teste',
        category: 'ipad',
        price: 4999,
        quantity: 1,
    },
    {
        id: 12,
        img: 'img/iphones/ipad-air.jpg',
        nome: 'iPad Air',
        descrcao: 'teste',
        category: 'ipad',
        price: 6999,
        quantity: 1,
    },
    {
        id: 13,
        img: 'img/iphones/ipad-pro.jpg',
        nome: 'iPad Pro',
        descrcao: 'teste',
        category: 'ipad',
        price: 9799,
        quantity: 1,
    },
    {
        id: 14,
        img: 'img/bebidas/agua com gas.jpg',
        nome: 'Água com gás',
        descrcao: 'teste',
        category: 'Mac',
        price: 2.99,
        quantity: 1,
    },
    {
        id: 15,
        img: 'img/bebidas/agua sem gas.jpg',
        nome: 'Água sem gás',
        descrcao: 'teste',
        category: 'Mac',
        price: 2.99,
        quantity: 1,
    },
    {
        id: 16,
        img: 'img/bebidas/coca.jpg',
        nome: 'Coca-cola',
        descrcao: 'teste',
        category: 'Mac',
        price: 4.50,
        quantity: 1,
    },
    {
        id: 17,
        img: 'img/bebidas/coca0.jpg',
        nome: 'Coca-cola 0',
        descrcao: 'teste',
        category: 'Mac',
        price: 4.50,
        quantity: 1,
    },
    {
        id: 18,
        img: 'img/bebidas/coca2l.jpg',
        nome: 'Coca-cola 2L',
        descrcao: 'teste',
        category: 'Mac',
        price: 11.80,
        quantity: 1,
    },
    {
        id: 19,
        img: 'img/bebidas/energetico branco.jpg',
        nome: 'Energético Ultra',
        descrcao: 'teste',
        category: 'Mac',
        price: 10.20,
        quantity: 1,
    },
    {
        id: 20,
        img: 'img/bebidas/energetico juice.jpg',
        nome: 'Energético juice',
        descrcao: 'teste',
        category: 'Mac',
        price: 10.20,
        quantity: 1,
    },
    {
        id: 21,
        img: 'img/bebidas/energetico tnt.jpg',
        nome: 'Energético TNT',
        descrcao: 'teste',
        category: 'Mac',
        price: 9.70,
        quantity: 1,
    },
    {
        id: 22,
        img: 'img/bebidas/energetico.jpg',
        nome: 'Energético',
        descrcao: 'teste',
        category: 'Mac',
        price: 10.20,
        quantity: 1,
    },
    {
        id: 23,
        img: 'img/bebidas/fanta laranja.jpg',
        nome: 'Fanta laranja',
        descrcao: 'teste',
        category: 'Mac',
        price: 4.30,
        quantity: 1,
    },
    {
        id: 24,
        img: 'img/bebidas/fanta uva.jpg',
        nome: 'Fanta uva',
        descrcao: 'teste',
        category: 'Mac',
        price: 4.30,
        quantity: 1,
    },
    {
        id: 25,
        img: 'img/bebidas/guarana.jpg',
        nome: 'Guaraná',
        descrcao: 'teste',
        category: 'Mac',
        price: 4.30,
        quantity: 1,
    },
    {
        id: 26,
        img: 'img/bebidas/limoneto.jpg',
        nome: 'Limoneto',
        descrcao: 'teste',
        category: 'Mac',
        price: 5.50,
        quantity: 1,
    },
    {
        id: 27,
        img: 'img/bebidas/pepsi.jpg',
        nome: 'Pepsi',
        descrcao: 'teste',
        category: 'Mac',
        price: 4.30,
        quantity: 1,
    },
]

export { produtos };