var produtos = [
    {
        id: 1,
        img: 'img/lanches/baco.jpeg',
        nome: 'Bacon mania',
        descrcao: '( Carne, queijo prato, catupiry e maionese Destak. )',
        category: 'iphone',
        price: 43.90,
        quantity: 1,
    },
    {
        id: 2,
        img: 'img/lanches/burger.jpeg',
        nome: 'X-burger',
        descrcao: '(Hambúrguer 150g, queijo prato, bacon fatiado, tomate, alface, batata palha e maionese)',
        category: 'iphone',
        price: 35.90,
        quantity: 1,
    },
    {
        id: 3,
        img: 'img/lanches/carne-queijo.jpeg',
        nome: 'PCQ',
        descrcao: '(Hambúrguer de 150g, queijo prato e maionese)',
        category: 'iphone',
        price: 23.90,
        quantity: 1,
    },
    {
        id: 4,
        img: 'img/lanches/carne.jpeg',
        nome: 'Pão com carne',
        descrcao: '( Carne, queijo prato, catupiry e maionese Destak. )',
        category: 'iphone',
        price: 29.90,
        quantity: 1,
    },
    {
        id: 5,
        img: 'img/lanches/catupiry.jpeg',
        nome: 'X-Catupity',
        descrcao: '(Hambúrguer 150g, queijo prato, catupiry, bacon fatiado e maionese)',
        category: 'iphone',
        price: 32.90,
        quantity: 1,
    },
    {
        id: 6,
        img: 'img/lanches/chedder.jpeg',
        nome: 'chicken Cheddar',
        descrcao: '( Frango, queijo prato, Cheddar e maionese Destak. )',
        category: 'iphone',
        price: 26.90,
        quantity: 1,
    },
    {
        id: 7,
        img: 'img/lanches/destak.jpeg',
        nome: 'Chachorro Destak',
        descrcao: '( Salsicha, presunto, mussarela, alface, batata, tomate, milho, maionese e catchup )',
        category: 'iphone',
        price: 20.90,
        quantity: 1,
    },
    {
        id: 8,
        img: 'img/lanches/provalone.jpeg',
        nome: 'X-Provalone',
        descrcao: '( Hambúrguer 150 g, queijo prato, bacon fatiado, tomate, alface, batata palha e maionese)',
        category: 'iphone',
        price: 31.90,
        quantity: 1,
    },
    {
        id: 14,
        img: 'img/bebidas/agua com gas.jpg',
        nome: 'Água com gás',
        descrcao: 'teste',
        category: 'Mac',
        price: 2.99,
        quantity: 1,
    },
    {
        id: 15,
        img: 'img/bebidas/agua sem gas.jpg',
        nome: 'Água sem gás',
        descrcao: 'teste',
        category: 'Mac',
        price: 2.99,
        quantity: 1,
    },
    {
        id: 16,
        img: 'img/bebidas/coca.jpg',
        nome: 'Coca-cola',
        descrcao: 'teste',
        category: 'Mac',
        price: 4.50,
        quantity: 1,
    },
    {
        id: 17,
        img: 'img/bebidas/coca0.jpg',
        nome: 'Coca-cola 0',
        descrcao: 'teste',
        category: 'Mac',
        price: 4.50,
        quantity: 1,
    },
    {
        id: 18,
        img: 'img/bebidas/coca2l.jpg',
        nome: 'Coca-cola 2L',
        descrcao: 'teste',
        category: 'Mac',
        price: 11.80,
        quantity: 1,
    },
    {
        id: 19,
        img: 'img/bebidas/energetico branco.jpg',
        nome: 'Energético Ultra',
        descrcao: 'teste',
        category: 'Mac',
        price: 10.20,
        quantity: 1,
    },
    {
        id: 20,
        img: 'img/bebidas/energetico juice.jpg',
        nome: 'Energético juice',
        descrcao: 'teste',
        category: 'Mac',
        price: 10.20,
        quantity: 1,
    },
    {
        id: 21,
        img: 'img/bebidas/energetico tnt.jpg',
        nome: 'Energético TNT',
        descrcao: 'teste',
        category: 'Mac',
        price: 9.70,
        quantity: 1,
    },
    {
        id: 22,
        img: 'img/bebidas/energetico.jpg',
        nome: 'Energético',
        descrcao: 'teste',
        category: 'Mac',
        price: 10.20,
        quantity: 1,
    },
    {
        id: 23,
        img: 'img/bebidas/fanta laranja.jpg',
        nome: 'Fanta laranja',
        descrcao: 'teste',
        category: 'Mac',
        price: 4.30,
        quantity: 1,
    },
    {
        id: 24,
        img: 'img/bebidas/fanta uva.jpg',
        nome: 'Fanta uva',
        descrcao: 'teste',
        category: 'Mac',
        price: 4.30,
        quantity: 1,
    },
    {
        id: 25,
        img: 'img/bebidas/guarana.jpg',
        nome: 'Guaraná',
        descrcao: 'teste',
        category: 'Mac',
        price: 4.30,
        quantity: 1,
    },
    {
        id: 26,
        img: 'img/bebidas/limoneto.jpg',
        nome: 'Limoneto',
        descrcao: 'teste',
        category: 'Mac',
        price: 5.50,
        quantity: 1,
    },
    {
        id: 27,
        img: 'img/bebidas/pepsi.jpg',
        nome: 'Pepsi',
        descrcao: 'teste',
        category: 'Mac',
        price: 4.30,
        quantity: 1,
    },
]

export { produtos };