var produtos = [
    {
        id: 1,
        img: 'img/iphones/iphone-SE.jpg',
        nome: 'iPhone SE',
        descrcao: 'teste',
        category: 'iphone',
        price: 4299,
        quantity: 1,
    },
    {
        id: 2,
        img: 'img/iphones/iphone-13.jpg',
        nome: 'iPhone 13',
        descrcao: 'teste',
        category: 'iphone',
        price: 5499,
        quantity: 1,
    },
    {
        id: 3,
        img: 'img/iphones/iphone-14.jpg',
        nome: 'iPhone 14',
        descrcao: 'teste',
        category: 'iphone',
        price: 5999,
        quantity: 1,
    },
    {
        id: 4,
        img: 'img/iphones/iphone14plus.png',
        nome: 'iPhone 14 Plus',
        descrcao: 'teste',
        category: 'iphone',
        price: 6499,
        quantity: 1,
    },
    {
        id: 5,
        img: 'img/iphones/iphone-15.jpg',
        nome: 'iPhone 15',
        descrcao: 'teste',
        category: 'iphone',
        price: 7299,
        quantity: 1,
    },
    {
        id: 6,
        img: 'img/iphones/iphone15plus.png',
        nome: 'iPhone 15 Plus',
        descrcao: 'teste',
        category: 'iphone',
        price: 8299,
        quantity: 1,
    },
    {
        id: 7,
        img: 'img/iphones/iphone-15-pro.jpg',
        nome: 'iPhone 15 Pro',
        descrcao: 'teste',
        category: 'iphone',
        price: 9299,
        quantity: 1,
    },
    {
        id: 8,
        img: 'img/iphones/iphone15promax.png',
        nome: 'iPhone 15 Pro Max',
        descrcao: 'teste',
        category: 'iphone',
        price: 10999,
        quantity: 1,
    },
    {
        id: 9,
        img: 'img/iphones/ipad-card.jpg',
        nome: 'ipad mini',
        descrcao: 'teste',
        category: 'ipad',
        price: 5999,
        quantity: 1,
    },
    {
        id: 10,
        img: 'img/iphones/ipad-9.jpg',
        nome: 'iPadiPad (9ª geração)',
        descrcao: 'teste',
        category: 'ipad',
        price: 3799,
        quantity: 1,
    },
    {
        id: 11,
        img: 'img/iphones/ipad-10.jpg',
        nome: 'iPadiPad (10ª geração)',
        descrcao: 'teste',
        category: 'ipad',
        price: 4999,
        quantity: 1,
    },
    {
        id: 12,
        img: 'img/iphones/ipad-air.jpg',
        nome: 'iPad Air',
        descrcao: 'teste',
        category: 'ipad',
        price: 6999,
        quantity: 1,
    },
    {
        id: 13,
        img: 'img/iphones/ipad-pro.jpg',
        nome: 'iPad Pro',
        descrcao: 'teste',
        category: 'ipad',
        price: 9799,
        quantity: 1,
    },
    {
        id: 14,
        img: 'img/iphones/pro-display.jpg',
        nome: 'Pro Display XDR',
        descrcao: 'teste',
        category: 'Mac',
        price: 44999,
        quantity: 1,
    },
    {
        id: 15,
        img: 'img/iphones/mac-pro.jpg',
        nome: 'Mac Pro',
        descrcao: 'teste',
        category: 'Mac',
        price: 74999,
        quantity: 1,
    },
    {
        id: 16,
        img: 'img/iphones/studio-display.jpg',
        nome: 'Studio Display',
        descrcao: 'teste',
        category: 'Mac',
        price: 16599,
        quantity: 1,
    },
    {
        id: 17,
        img: 'img/iphones/mac-studio.jpg',
        nome: 'Mac Studio',
        descrcao: 'teste',
        category: 'Mac',
        price: 22999,
        quantity: 1,
    },
    {
        id: 18,
        img: 'img/iphones/mac-mini.jpg',
        nome: 'Mac mini',
        descrcao: 'teste',
        category: 'Mac',
        price: 7499,
        quantity: 1,
    },
    {
        id: 19,
        img: 'img/iphones/imac.jpg',
        nome: 'iMac',
        descrcao: 'teste',
        category: 'Mac',
        price: 14499,
        quantity: 1,
    },
    {
        id: 20,
        img: 'img/iphones/macbookpro.jpg',
        nome: 'MacBook Pro 14 pol.',
        descrcao: 'teste',
        category: 'Mac',
        price: 18499,
        quantity: 1,
    },
    {
        id: 21,
        img: 'img/iphones/macbook-air.jpg',
        nome: 'MacBook Air',
        descrcao: 'teste',
        category: 'Mac',
        price: 12499,
        quantity: 1,
    },
    {
        id: 22,
        img: 'img/iphones/macbook-air-20.jpg',
        nome: 'MacBook Air',
        descrcao: 'teste',
        category: 'Mac',
        price: 11599,
        quantity: 1,
    },
]

export { produtos };